import { test, expect } from '@playwright/test';

test.only('test', async ({ page }) => {
  await page.goto('https://test.folloit.com/login');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('anithatestuser7@yopmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.locator('.dropdown-multiselect__caret').first().click();
  await page.locator('div').filter({ hasText: /^New Delivery Booking$/ }).click();
  await page.getByText('Select Template').click();
  await page.getByText('October').click();
  await page.getByRole('switch').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('alert', { name: 'Delivery Booking Created' })).toBeVisible();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.getByText('New Delivery Booking').first().click();
  await page.getByText('New Crane Booking').click();
  await page.getByRole('textbox', { name: 'Enter Description' }).click();
  await page.getByRole('textbox', { name: 'Enter Description' }).fill('test crane');
  await page.locator('span').filter({ hasText: 'Choose Gate*' }).first().click();
  await page.getByRole('listitem').filter({ hasText: 'North gate' }).click();
  await page.locator('span').filter({ hasText: 'Choose Equipment' }).first().click();
  await page.getByText('Mobile crane').click();
  await page.getByRole('textbox', { name: 'Picking From' }).click();
  await page.getByRole('textbox', { name: 'Picking From' }).fill('234');
  await page.getByRole('textbox', { name: 'Picking To' }).click();
  await page.getByRole('textbox', { name: 'Picking To' }).fill('456');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('td').filter({ hasText: '7 AM8 AM9 AM10 AM11 AM12 PM1' }).click();
  await page.locator('.fc-timeGridDay-view > .fc-scrollgrid > tbody > .fc-scrollgrid-section > td > .fc-scroller-harness > .fc-scroller').click();
  await page.locator('.timeslot-modal-body').click();
  await page.locator('.fc-timeGridDay-view > .fc-scrollgrid > tbody > .fc-scrollgrid-section > td > .fc-scroller-harness > .fc-scroller').click();
  await page.locator('tr:nth-child(49) > .fc-timegrid-slot.fc-timegrid-slot-lane').click();
  await page.getByRole('img', { name: 'Next Day' }).click();
  await page.locator('tr:nth-child(5) > .fc-timegrid-slot.fc-timegrid-slot-lane').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('alert', { name: 'Crane delivery end date and' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('alert', { name: 'Crane delivery end date and' })).toBeVisible();
});