import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://test.folloit.com/login');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('anithatestuser7@yopmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page.getByRole('img', { name: 'Follo' })).toBeVisible();
  //creating concrete booking
  await page.getByRole('button', { name: ' Add' }).click();
  await page.getByText('New Delivery Booking').first().click();
  await page.getByText('New Concrete Booking').click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('test concrete');
  await page.locator('span').filter({ hasText: 'Choose Gate*' }).first().click();
  await page.getByText('North gate').click();
  await page.locator('span').filter({ hasText: 'Choose Equipment' }).first().click();
  await page.getByText('Mobile crane').click();
  await page.locator('.timeslot-modal-body').click();
  await page.locator('tr:nth-child(49) > .fc-timegrid-slot.fc-timegrid-slot-lane').click();
  await page.locator('span').filter({ hasText: 'Does Not Repeat x' }).first().click();
  await page.getByText('Daily').click();
  await page.locator('.input-group-text').click();
  await page.getByRole('gridcell', { name: '25', exact: true }).click();
  await page.locator('span').filter({ hasText: 'Choose Truck Type' }).first().click();
  await page.getByText('Flatbed Truck').click();
  await page.getByText('Flatbed Truck').click();
  await page.locator('div').filter({ hasText: 'Cancel Submit' }).nth(4).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('alert', { name: 'Concrete Booking Created' })).toBeVisible();
  await page.getByRole('button', { name: ' Add' }).click();
  //Creating inspection booking
  await page.getByText('New Delivery Booking').first().click();
  await page.getByText('New Inspection Booking').click();
  await page.getByRole('textbox', { name: 'Enter Description' }).click();
  await page.getByRole('textbox', { name: 'Enter Description' }).fill('testing inspection');
  await page.getByRole('switch').click();
  await page.locator('span').filter({ hasText: 'Choose Equipment' }).first().click();
  await page.getByText('Mobile crane').click();
  await page.locator('span').filter({ hasText: 'Choose Gate*' }).first().click();
  await page.getByRole('listitem').filter({ hasText: 'East Gate' }).click();
  await page.getByText('Picking From*').click();
  await page.getByRole('textbox', { name: 'Picking From' }).click();
  await page.getByRole('textbox', { name: 'Picking From' }).fill('234678');
  await page.getByRole('textbox', { name: 'Picking To' }).click();
  await page.getByRole('textbox', { name: 'Picking To' }).click();
  await page.getByRole('textbox', { name: 'Picking To' }).fill('789');
  await page.getByText('Select the inspection type').click();
  await page.getByRole('listitem').filter({ hasText: 'Special Inspection' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Special Inspection' }).click();
  await page.getByRole('img', { name: 'Date' }).click();
  await page.getByLabel('calendar').getByText('25', { exact: true }).click();
  await page.locator('span').filter({ hasText: 'Choose Truck Type' }).first().click();
  await page.getByText('Dump Truck').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('div').filter({ hasText: 'Vehicle TypeHeavy Duty xLight' }).nth(4).click();
  await page.locator('div').filter({ hasText: 'Vehicle TypeHeavy Duty xLight' }).nth(4).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('alert', { name: 'Please fill all the required' })).toBeVisible();
  await page.locator('tr:nth-child(49) > .fc-timegrid-slot.fc-timegrid-slot-lane').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('alert', { name: 'Inspection Booking Created' })).toBeVisible();
  await page.getByLabel('17', { exact: true }).getByText('+3 more').click();
  await expect(page.getByLabel('17', { exact: true }).getByText('+3 more')).toBeVisible();
  await page.getByLabel('17', { exact: true }).getByText('+3 more').click();
  await page.locator('.fc-popover-body > div:nth-child(3) > .fc-event').click();
  await page.locator('div').filter({ hasText: 'Inspection Details Select' }).nth(1).click();
  await page.getByRole('paragraph').filter({ hasText: /^testing inspection$/ }).click();
  await page.getByRole('button', { name: 'Close' }).click();
});