import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://test.folloit.com/home');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('anithatestusersc7@yopmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page.getByRole('img', { name: 'Follo' })).toBeVisible();
  await page.getByText('Project', { exact: true }).click();
  await page.getByRole('link', { name: 'A Project Down Arrow' }).click();
  await page.getByRole('link', { name: 'A Project Down Arrow' }).click();
  await page.getByRole('link', { name: 'ActiveDashboard Dashboard' }).click();
  await page.locator('app-dashboard section').click();
  await page.locator('a').filter({ hasText: 'All Bookings' }).click();
  await page.getByRole('link', { name: 'Delivery Bookings', exact: true }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.locator('span').filter({ hasText: 'Select Template' }).first().click();
  await page.locator('span').filter({ hasText: 'Select Template' }).first().click();
  await page.getByText('Select Template').click();
  await page.getByText('Delivery Booking Template Sc').click();
  await page.getByRole('dialog').click();
  await page.getByText('Vehicle TypeLight DutyMedium').click();
  await page.getByText('Vehicle TypeLight DutyMedium').click();
  await page.getByText('Choose Truck Type').click();
  await page.getByRole('listitem').filter({ hasText: 'Dump Truck' }).click();
  await page.getByText('Heavy Duty xLight DutyMedium').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('switch').click();
  await page.getByText('Definable Feature Of WorkChoose Definable Feature Of Work (Scope)Select').click();
  await page.getByText('Concrete', { exact: true }).click();
  await page.locator('tr:nth-child(49) > .fc-timegrid-slot.fc-timegrid-slot-lane').click();
  await page.locator('span').filter({ hasText: 'Does Not Repeat x' }).first().click();
  await page.getByText('Daily').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
});