import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://test.folloit.com/login');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('anithatestuser7@yopmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page.getByRole('alert', { name: 'Let\'s get to work!' })).toBeVisible();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.locator('span').filter({ hasText: 'Select Template' }).first().click();
  await page.getByText('testing automate').click();
  await page.getByRole('switch').click();
  await page.locator('tr:nth-child(45) > .fc-timegrid-slot.fc-timegrid-slot-lane').click();
  await page.getByRole('combobox').selectOption('Week');
  await page.getByText('M', { exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('M', { exact: true }).click();
  await page.getByText('T', { exact: true }).first().click();
  await page.getByText('T', { exact: true }).first().click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('img', { name: 'Follo' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.locator('span').filter({ hasText: 'Select Template' }).first().click();
  await page.getByText('testing automate').click();
  await page.getByText('New Delivery Booking').first().click();
  await page.getByText('New Crane Booking').click();
  await page.getByRole('textbox', { name: 'Enter Description' }).click();
  await page.getByRole('textbox', { name: 'Enter Description' }).fill('testing crane');
  await page.getByText('Choose Gate*').click();
  await page.getByRole('dialog').click();
  await page.locator('span').filter({ hasText: 'Choose Gate*' }).first().click();
  await page.getByText('East Gate').click();
  await page.locator('span').filter({ hasText: 'Choose Equipment' }).first().click();
  await page.getByRole('listitem').filter({ hasText: 'Mobile crane' }).click();
  await page.getByRole('textbox', { name: 'Picking From' }).click();
  await page.getByRole('textbox', { name: 'Picking From' }).fill('234');
  await page.getByRole('textbox', { name: 'Picking To' }).click();
  await page.getByRole('textbox', { name: 'Picking To' }).fill('456');
  await page.getByRole('textbox', { name: 'Picking To' }).click();
  await page.locator('tr:nth-child(40) > .fc-timegrid-slot.fc-timegrid-slot-lane').click();
  await page.locator('span').filter({ hasText: 'Does Not Repeat x' }).first().click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('alert', { name: 'Crane Booking Created' })).toBeVisible();
  await page.getByLabel('18', { exact: true }).getByText('+6 more').click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.getByText('Select Template').click();
  await page.getByText('testing automate').click();
  await page.getByText('New Delivery Booking').first().click();
  await page.getByText('New Concrete Booking').click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('testing concreate');
  await page.locator('span').filter({ hasText: 'Choose Equipment' }).first().click();
  await page.getByText('Non crane').click();
  await page.locator('span').filter({ hasText: 'Choose Gate*' }).first().click();
  await page.getByText('South gate').click();
  await page.locator('tr:nth-child(45) > .fc-timegrid-slot.fc-timegrid-slot-lane').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('alert', { name: 'Concrete Booking Created' }).click();
});